# Numpy Package

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [13]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import numpy as np
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [12]:
np.arange(10.1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(20,10)  # 1st arg must be less then 2nd arg

array([], dtype=int64)

In [17]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [18]:
np.arange(10,30,5,6)

TypeError: Cannot interpret '6' as a data type

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [28]:
np.zeros(2,2)

TypeError: Cannot interpret '2' as a data type

In [22]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
np.ones([10,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.random.rand(3,4)

array([[0.09991995, 0.62983881, 0.63826241, 0.96576252],
       [0.04061386, 0.98749232, 0.07541472, 0.73784341],
       [0.08863501, 0.53164989, 0.98098091, 0.62532235]])

In [32]:
np.random.randint(2)

0

In [35]:
np.random.randint(10,40,(10,10))

array([[33, 35, 11, 27, 35, 30, 23, 27, 15, 12],
       [13, 25, 25, 19, 18, 26, 33, 37, 18, 12],
       [14, 29, 16, 24, 35, 31, 15, 22, 26, 20],
       [13, 33, 29, 25, 36, 11, 14, 34, 15, 33],
       [23, 18, 17, 17, 30, 34, 20, 39, 18, 15],
       [19, 15, 36, 17, 35, 25, 16, 19, 23, 30],
       [30, 26, 22, 31, 27, 31, 27, 28, 36, 30],
       [23, 21, 28, 29, 23, 35, 14, 22, 39, 21],
       [35, 22, 13, 20, 10, 14, 35, 28, 29, 21],
       [29, 20, 20, 28, 12, 28, 23, 37, 26, 12]], dtype=int32)

In [39]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# slicing and matrix

In [60]:
b = np.random.randint(10,20,(5,4))

In [51]:
b

array([[12, 15, 12, 12],
       [17, 13, 16, 15],
       [13, 17, 11, 14],
       [15, 19, 11, 15],
       [13, 14, 18, 16]], dtype=int32)

In [46]:
b[:]

array([[19, 14, 19, 17],
       [11, 15, 14, 10],
       [14, 19, 19, 13],
       [14, 17, 19, 17],
       [12, 17, 19, 16]], dtype=int32)

In [47]:
b[0]

array([19, 14, 19, 17], dtype=int32)

In [48]:
b[0:5]

array([[19, 14, 19, 17],
       [11, 15, 14, 10],
       [14, 19, 19, 13],
       [14, 17, 19, 17],
       [12, 17, 19, 16]], dtype=int32)

In [52]:
b[0,1]

np.int32(15)

In [53]:
b

array([[12, 15, 12, 12],
       [17, 13, 16, 15],
       [13, 17, 11, 14],
       [15, 19, 11, 15],
       [13, 14, 18, 16]], dtype=int32)

In [54]:
b[::-1]

array([[13, 14, 18, 16],
       [15, 19, 11, 15],
       [13, 17, 11, 14],
       [17, 13, 16, 15],
       [12, 15, 12, 12]], dtype=int32)

In [56]:
print(b)

[[19 11 13 11]
 [10 12 12 16]
 [19 18 11 15]
 [15 12 10 11]
 [13 16 17 12]]


In [61]:
b

array([[16, 18, 16, 17],
       [19, 18, 17, 11],
       [18, 19, 11, 10],
       [14, 18, 18, 10],
       [19, 17, 13, 10]], dtype=int32)

In [62]:
print(b)

[[16 18 16 17]
 [19 18 17 11]
 [18 19 11 10]
 [14 18 18 10]
 [19 17 13 10]]


In [64]:
a= b.max()
print(a)

19


In [65]:
a= b.mean()
print(a)

15.45


In [66]:
b

array([[16, 18, 16, 17],
       [19, 18, 17, 11],
       [18, 19, 11, 10],
       [14, 18, 18, 10],
       [19, 17, 13, 10]], dtype=int32)

In [68]:
b[-3,-3]

np.int32(19)

In [69]:
b[:3]

array([[16, 18, 16, 17],
       [19, 18, 17, 11],
       [18, 19, 11, 10]], dtype=int32)

In [70]:
b

array([[16, 18, 16, 17],
       [19, 18, 17, 11],
       [18, 19, 11, 10],
       [14, 18, 18, 10],
       [19, 17, 13, 10]], dtype=int32)

In [71]:
b[1]

array([19, 18, 17, 11], dtype=int32)

In [72]:
b[:,1]

array([18, 18, 19, 18, 17], dtype=int32)

In [73]:
b

array([[16, 18, 16, 17],
       [19, 18, 17, 11],
       [18, 19, 11, 10],
       [14, 18, 18, 10],
       [19, 17, 13, 10]], dtype=int32)

In [74]:
b[1:4,1:4]

array([[18, 17, 11],
       [19, 11, 10],
       [18, 18, 10]], dtype=int32)

# Masking

In [76]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [77]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [78]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [79]:
c = np.random.randint(10,20,(5,4))
c

array([[12, 18, 12, 10],
       [13, 15, 15, 17],
       [16, 17, 19, 10],
       [11, 16, 10, 10],
       [19, 14, 16, 17]], dtype=int32)

In [80]:
type(c)

numpy.ndarray

In [81]:
c[:]

array([[12, 18, 12, 10],
       [13, 15, 15, 17],
       [16, 17, 19, 10],
       [11, 16, 10, 10],
       [19, 14, 16, 17]], dtype=int32)

In [82]:
c[1:3]

array([[13, 15, 15, 17],
       [16, 17, 19, 10]], dtype=int32)

In [83]:
c[2,3]

np.int32(10)

In [84]:
c[1,-1]

np.int32(17)

In [85]:
c[0:-2]

array([[12, 18, 12, 10],
       [13, 15, 15, 17],
       [16, 17, 19, 10]], dtype=int32)

In [86]:
c

array([[12, 18, 12, 10],
       [13, 15, 15, 17],
       [16, 17, 19, 10],
       [11, 16, 10, 10],
       [19, 14, 16, 17]], dtype=int32)

In [87]:
c[-5,-3]

np.int32(18)

In [88]:
c[-4,-2]

np.int32(15)

In [89]:
arr2 = np.random.randint(1,100,(10,10))
arr2

array([[21, 29, 66, 84, 96, 79, 94, 66, 41, 49],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [51, 69, 24, 48, 66, 52, 54,  5, 60,  8],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [96, 45, 22, 21, 86, 48, 62, 48, 88, 51],
       [48, 61, 23, 76, 18, 96, 85, 38, 45, 30],
       [83, 54, 22, 15, 52, 28, 77, 26, 25, 76],
       [86, 10, 66, 11, 32, 19, 61, 19, 42, 97]], dtype=int32)

In [90]:
arr2[0:0]

array([], shape=(0, 10), dtype=int32)

In [91]:
arr2[:]

array([[21, 29, 66, 84, 96, 79, 94, 66, 41, 49],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [51, 69, 24, 48, 66, 52, 54,  5, 60,  8],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [96, 45, 22, 21, 86, 48, 62, 48, 88, 51],
       [48, 61, 23, 76, 18, 96, 85, 38, 45, 30],
       [83, 54, 22, 15, 52, 28, 77, 26, 25, 76],
       [86, 10, 66, 11, 32, 19, 61, 19, 42, 97]], dtype=int32)

In [92]:
arr2[:4]

array([[21, 29, 66, 84, 96, 79, 94, 66, 41, 49],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96]], dtype=int32)

In [93]:
arr2[1:4]

array([[81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96]], dtype=int32)

In [95]:
arr2

array([[21, 29, 66, 84, 96, 79, 94, 66, 41, 49],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [51, 69, 24, 48, 66, 52, 54,  5, 60,  8],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [96, 45, 22, 21, 86, 48, 62, 48, 88, 51],
       [48, 61, 23, 76, 18, 96, 85, 38, 45, 30],
       [83, 54, 22, 15, 52, 28, 77, 26, 25, 76],
       [86, 10, 66, 11, 32, 19, 61, 19, 42, 97]], dtype=int32)

In [96]:
arr2[-5:5]

array([], shape=(0, 10), dtype=int32)

In [97]:
arr2[-5,5]

np.int32(5)

In [98]:
arr2[::-1]

array([[86, 10, 66, 11, 32, 19, 61, 19, 42, 97],
       [83, 54, 22, 15, 52, 28, 77, 26, 25, 76],
       [48, 61, 23, 76, 18, 96, 85, 38, 45, 30],
       [96, 45, 22, 21, 86, 48, 62, 48, 88, 51],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [51, 69, 24, 48, 66, 52, 54,  5, 60,  8],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [21, 29, 66, 84, 96, 79, 94, 66, 41, 49]], dtype=int32)

In [99]:
arr2

array([[21, 29, 66, 84, 96, 79, 94, 66, 41, 49],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [51, 69, 24, 48, 66, 52, 54,  5, 60,  8],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [96, 45, 22, 21, 86, 48, 62, 48, 88, 51],
       [48, 61, 23, 76, 18, 96, 85, 38, 45, 30],
       [83, 54, 22, 15, 52, 28, 77, 26, 25, 76],
       [86, 10, 66, 11, 32, 19, 61, 19, 42, 97]], dtype=int32)

In [100]:
arr2[::-2]

array([[86, 10, 66, 11, 32, 19, 61, 19, 42, 97],
       [48, 61, 23, 76, 18, 96, 85, 38, 45, 30],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61]], dtype=int32)

In [101]:
arr2

array([[21, 29, 66, 84, 96, 79, 94, 66, 41, 49],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [51, 69, 24, 48, 66, 52, 54,  5, 60,  8],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [96, 45, 22, 21, 86, 48, 62, 48, 88, 51],
       [48, 61, 23, 76, 18, 96, 85, 38, 45, 30],
       [83, 54, 22, 15, 52, 28, 77, 26, 25, 76],
       [86, 10, 66, 11, 32, 19, 61, 19, 42, 97]], dtype=int32)

In [102]:
arr2[:-3]

array([[21, 29, 66, 84, 96, 79, 94, 66, 41, 49],
       [81, 88, 12, 43, 78, 53, 48, 90, 56, 61],
       [80, 31, 71, 16, 97, 78, 35, 86, 64,  4],
       [90,  1, 53, 18, 86, 59, 54, 96, 10, 96],
       [51, 69, 24, 48, 66, 52, 54,  5, 60,  8],
       [32, 25, 63, 14, 95,  5, 68, 70, 17,  1],
       [96, 45, 22, 21, 86, 48, 62, 48, 88, 51]], dtype=int32)

In [103]:
arr2.max()

np.int32(97)

In [104]:
arr2.min()

np.int32(1)

In [105]:
arr2.mean()

np.float64(51.75)

In [108]:
from numpy import *
a = array([1,2,3,4,5])
type(a)
median(a)

np.float64(3.0)

In [111]:
arr = array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [114]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [115]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [116]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [121]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [122]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [123]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [124]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [125]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [126]:
row =4
column = 5

In [127]:
row

4

In [128]:
column

5

In [129]:
mat[row,column]

np.int64(45)

In [130]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [131]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [132]:
mat[:,column]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [133]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [134]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [135]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [136]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
mat[0:10,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [138]:
mat[0:10:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [139]:
mat[0:10,2:4]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [140]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [141]:
mat[0,3]

np.int64(3)

In [142]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [143]:
mat[2:4,4:6]

array([[24, 25],
       [34, 35]])

# Masking

In [144]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
id(mat)

2651585110704

In [146]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [148]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [149]:
mat[mat==50]

array([50])

In [150]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [151]:
a1= mat[mat==50]

In [152]:
a1

array([50])