# Numpy Crash Course

In [2]:
import numpy as np

In [3]:
np.__version__

'2.1.3'

In [4]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(30,20) # First argument always less then 2nd argument

array([], dtype=int64)

In [13]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [14]:
np.arange(10,10)

array([], dtype=int64)

In [15]:
np.arange(10,20,5) # startvalue,endvalue,steps (end value = endvalue -1) hence 20 will not print

array([10, 15])

In [16]:
np.zeros(3)  # Parametner tuning

array([0., 0., 0.])

In [17]:
np.zeros(3,dtype=int)  # hyperametner tuning

array([0, 0, 0])

In [21]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [22]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [23]:
n = (6,7)

In [24]:
np.zeros(n)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

- Same ways we have 'ones' method which will print 1 

In [29]:
r = range(5)

In [30]:
r


range(0, 5)

In [31]:
for i in r:
    print (i)

0
1
2
3
4


In [32]:
np.random.rand(5)

array([0.6733427 , 0.25733263, 0.00707713, 0.78247239, 0.58043558])

In [33]:
np.random.rand(5)

array([0.4940697 , 0.78929083, 0.5440551 , 0.07472941, 0.29897701])

In [35]:
np.random.rand(2,4)

array([[0.32501837, 0.35985847, 0.79445858, 0.24740645],
       [0.06217553, 0.31318773, 0.84051739, 0.55998015]])

In [39]:
np.random.randint(2,4)  # 2nd argument is exclusive

3

In [40]:
np.random.randint(1,10,5)  # This means generate 5 digit between 1 to 9

array([5, 8, 4, 1, 3], dtype=int32)

In [43]:
np.random.randint(10,40,(5,5)) # This means generate 5*5 matrics with random digit between 10 to 39

array([[29, 21, 22, 31, 32],
       [35, 34, 39, 36, 30],
       [33, 25, 19, 30, 15],
       [30, 28, 12, 31, 29],
       [34, 26, 17, 13, 16]], dtype=int32)

In [48]:
np.arange(1,17).reshape(4,4)  # This means generate 4*4 matrics with digit starting from 1 to 16. total 16 digit = 4*4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
np.arange(1,17).reshape(16,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [50]:
np.arange(1,17).reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [55]:
b= np.random.randint(10,20,(5,4))

In [56]:
b

array([[15, 16, 19, 11],
       [18, 19, 12, 16],
       [10, 17, 10, 15],
       [19, 11, 13, 13],
       [15, 13, 11, 15]], dtype=int32)

In [57]:
type(b)

numpy.ndarray

In [58]:
b[:]

array([[15, 16, 19, 11],
       [18, 19, 12, 16],
       [10, 17, 10, 15],
       [19, 11, 13, 13],
       [15, 13, 11, 15]], dtype=int32)

In [59]:
b[1:3]

array([[18, 19, 12, 16],
       [10, 17, 10, 15]], dtype=int32)

In [60]:
b[1,2]

np.int32(12)

- this way we can do slicing in matrix

# Operations

In [61]:
a = np.random.randint(10,20,10)
a

array([12, 10, 13, 14, 16, 16, 12, 16, 13, 18], dtype=int32)

In [62]:
arr2 = np.random.randint(10,20,(10,10))

In [63]:
arr2

array([[18, 13, 12, 19, 17, 14, 13, 13, 17, 12],
       [10, 15, 18, 13, 10, 12, 13, 15, 16, 16],
       [11, 10, 15, 16, 18, 19, 18, 12, 15, 10],
       [17, 15, 18, 10, 17, 17, 15, 15, 18, 18],
       [16, 17, 19, 16, 10, 10, 14, 17, 11, 11],
       [15, 14, 10, 14, 18, 18, 17, 11, 19, 16],
       [10, 12, 19, 16, 17, 12, 10, 17, 11, 18],
       [16, 15, 12, 14, 15, 12, 12, 12, 10, 12],
       [14, 17, 15, 15, 11, 15, 16, 13, 19, 15],
       [10, 12, 13, 13, 11, 19, 14, 10, 15, 18]], dtype=int32)

In [64]:
arr2[:]

array([[18, 13, 12, 19, 17, 14, 13, 13, 17, 12],
       [10, 15, 18, 13, 10, 12, 13, 15, 16, 16],
       [11, 10, 15, 16, 18, 19, 18, 12, 15, 10],
       [17, 15, 18, 10, 17, 17, 15, 15, 18, 18],
       [16, 17, 19, 16, 10, 10, 14, 17, 11, 11],
       [15, 14, 10, 14, 18, 18, 17, 11, 19, 16],
       [10, 12, 19, 16, 17, 12, 10, 17, 11, 18],
       [16, 15, 12, 14, 15, 12, 12, 12, 10, 12],
       [14, 17, 15, 15, 11, 15, 16, 13, 19, 15],
       [10, 12, 13, 13, 11, 19, 14, 10, 15, 18]], dtype=int32)

In [65]:
arr2[0:5]

array([[18, 13, 12, 19, 17, 14, 13, 13, 17, 12],
       [10, 15, 18, 13, 10, 12, 13, 15, 16, 16],
       [11, 10, 15, 16, 18, 19, 18, 12, 15, 10],
       [17, 15, 18, 10, 17, 17, 15, 15, 18, 18],
       [16, 17, 19, 16, 10, 10, 14, 17, 11, 11]], dtype=int32)

In [66]:
arr2[1,4]  # This means value from 1st row (count from top start with 0) and 4th column (count from right start with 0)

np.int32(10)

In [68]:
arr2[-5,-5]

np.int32(18)

In [69]:
arr2

array([[18, 13, 12, 19, 17, 14, 13, 13, 17, 12],
       [10, 15, 18, 13, 10, 12, 13, 15, 16, 16],
       [11, 10, 15, 16, 18, 19, 18, 12, 15, 10],
       [17, 15, 18, 10, 17, 17, 15, 15, 18, 18],
       [16, 17, 19, 16, 10, 10, 14, 17, 11, 11],
       [15, 14, 10, 14, 18, 18, 17, 11, 19, 16],
       [10, 12, 19, 16, 17, 12, 10, 17, 11, 18],
       [16, 15, 12, 14, 15, 12, 12, 12, 10, 12],
       [14, 17, 15, 15, 11, 15, 16, 13, 19, 15],
       [10, 12, 13, 13, 11, 19, 14, 10, 15, 18]], dtype=int32)

In [70]:
arr2[::-1]

array([[10, 12, 13, 13, 11, 19, 14, 10, 15, 18],
       [14, 17, 15, 15, 11, 15, 16, 13, 19, 15],
       [16, 15, 12, 14, 15, 12, 12, 12, 10, 12],
       [10, 12, 19, 16, 17, 12, 10, 17, 11, 18],
       [15, 14, 10, 14, 18, 18, 17, 11, 19, 16],
       [16, 17, 19, 16, 10, 10, 14, 17, 11, 11],
       [17, 15, 18, 10, 17, 17, 15, 15, 18, 18],
       [11, 10, 15, 16, 18, 19, 18, 12, 15, 10],
       [10, 15, 18, 13, 10, 12, 13, 15, 16, 16],
       [18, 13, 12, 19, 17, 14, 13, 13, 17, 12]], dtype=int32)

In [71]:
arr2[::-2]

array([[10, 12, 13, 13, 11, 19, 14, 10, 15, 18],
       [16, 15, 12, 14, 15, 12, 12, 12, 10, 12],
       [15, 14, 10, 14, 18, 18, 17, 11, 19, 16],
       [17, 15, 18, 10, 17, 17, 15, 15, 18, 18],
       [10, 15, 18, 13, 10, 12, 13, 15, 16, 16]], dtype=int32)

In [72]:
arr2.max()

np.int32(19)

In [73]:
arr2.min()

np.int32(10)

# without import, finding median, mode

In [74]:
arr

array([0, 1, 2, 3, 4, 5])

In [75]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [76]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [77]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [79]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
arr.reshape(2,3,order='F') 

array([[0, 2, 4],
       [1, 3, 5]])

In [81]:
arr.reshape(2,3,order='A') 

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [84]:
mat = np.arange(0,100).reshape(10,10)

In [85]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
row =4
col =5

In [87]:
mat[row,col]

np.int64(45)

In [88]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
mat[6]  # bydefault represent 6th row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [90]:
col =6

In [91]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [92]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [93]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [94]:
mat[1,4]

np.int64(14)

In [95]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [99]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [98]:
mat[2:6,2:4] # 2:6 <--this will take only row,2:4 <-- this will take only column

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [100]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [102]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Masking

In [103]:
mat # We call it also filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
id(mat)

3144054541456

In [105]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [107]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])